config/routes.rb
Rails.application.routes.draw do

  mount API::Base => '/'

  root 'infos#index'
  resources :infos

end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController


  def index
    @infos = Info.all
  end
  #
  # def show
  #   # got data from before_action
  # end
  #
  # def new
  #   @info = Info.new
  # end
  #
  # def create
  #   @info = Info.create(info_params)
  #   if @info.save
  #     redirect_to :back
  #   else
  #     render 'new'
  #   end
  # end
  #
  # def edit
  #   # got data from before_action
  # end
  #
  # def update
  #   if @info.update(info_params)
  #   else
  #     render 'edit'
  #   end
  # end

  def destroy
    @info.destroy
    redirect_to info_path
  end

  private
    def info_params
      params.require(:info).permit(:id, :name, :category, :address)
    end

    def set_info
      @info = Info.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/index.html.haml
%h1
  Listing Infos
%table
  %thead
    %tr
      %th Name
      %th Category
      %th Address
  %tbody
    - @infos.each do |i|
      %tr
        %td
          = i.name
        %td
          = i.category
        %td
          = i.address

app/views/infos/new.html.haml
= form_for(@info) do |f|
  = f.label :name
  %br
  = f.text_field :name
  %br
  = f.label :category
  %br
  = f.text_field :category
  %br
  = f.label :address
  %br
  = f.text_field :address
  %br
  = f.submit

app/views/infos/show.html.haml
%p#notice
  = notice
%p
  Name:
  = @info.name
%p
  Category:
  = @info.category

= link_to 'Edit', edit_info_path(@info)
= link_to 'Back', infos_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>